name: pricing_calculator
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.2.8
  google_fonts: ^6.2.0
  logger: ^2.3.0
  flutter_screenutil: ^5.9.3
  universal_html: ^2.2.4
  visibility_detector: ^0.4.0+2
  firebase_core: ^3.6.0
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  flutter_fadein: ^2.0.0
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  toastification: ^2.3.0
  cloud_firestore: ^5.4.4
  slang: ^4.1.0
  slang_flutter: ^4.1.0
  flutter_markdown: ^0.7.4+1
  url_launcher_web: ^2.3.3
  web: ^1.1.0
  firebase_analytics: ^11.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  build_runner: ^2.4.13

  flutter_lints: ^4.0.0
  slang_build_runner: ^4.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
